version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Dokerhub
      - docker login -u naveen2112 -p $DOCKER_PASS
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/cicd-rorterraform
      - REPOSITORY_URI_NGINX=$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/cicd-nginxterraform

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
      - cd ./nginx
      - docker build -t $REPOSITORY_URI_NGINX:latest .
      - docker tag $REPOSITORY_URI_NGINX:latest $REPOSITORY_URI_NGINX:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker ror image...
      - docker push $REPOSITORY_URI:latest
      - echo push nginx image...
      - docker push $REPOSITORY_URI_NGINX:latest

      
