version: 0.2

phases:
  pre_build:
    commands:
      - echo Configuring AWS CLI...
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set region eu-north-1
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region  eu-north-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.eu-north-1.amazona
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/ror-application
      - REPOSITORY_URI_NGINX=$AWS_ACCOUNT_ID.dkr.ecr.eu-north-1.amazonaws.com/nginx-application

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:latest
      - cd ./nginx
      - docker build -t $REPOSITORY_URI_NGINX:latest .
      - docker tag $REPOSITORY_URI_NGINX:latest $REPOSITORY_URI_NGINX:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker ror image...
      - docker push $REPOSITORY_URI:latest
      - echo push nginx image...
      - docker push $REPOSITORY_URI_NGINX:latest
